name: 'Unity Setup'
description: 'Installs the Unity Editor and modules based on the build target and project settings.'
inputs:
  modules:
    description: 'Optional, Additional modules to install with the editor (i.e "webgl android lumin")'
    required: false
    default: ''
  version-file-path:
    description: 'Optional, specify a path to search for the unity project version text file. Use this if step fails to find a valid project version file.'
    required: false
    default: '**/ProjectSettings/ProjectVersion.txt'
outputs:
  editor-path:
    description: 'The path to the Unity Editor'
    #value: ${{ steps.validate.outputs.editor-path }}
  project-path:
    description: 'The path to the unity project'
    #value: ${{ steps.validate.outputs.project-path }}
runs:
  using: 'node16'
  main: 'index.js'