name: validate

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build-targets: 'StandaloneLinux64'
          - os: windows-latest
            build-targets: 'StandaloneWindows64'
          - os: macos-latest
            build-targets: 'StandaloneOSX'

    steps:
      - name: checkout self
        uses: actions/checkout@v3

      - run: npm install

      - name: checkout test project
        uses: actions/checkout@v3
        with:
          repository: xrtk/com.xrtk.test
          path: test-project

      - uses: ./ # xrtk/unity-setup
        id: unity-setup
        with:
          build-targets: ${{ matrix.build-targets }}

      - run: |
          echo "${{ env.UNITY_EDITOR_PATH }}"
          echo "${{ env.UNITY_PROJECT_PATH }}"